/* Main.c file generated by New Project wizard
 *
 * Created:   Mon Jul 3 2017
 * Processor: MSP430F2132
 * Compiler:  GCC for MSP430
 */

#include <MSP430.h>

void main ()
 { 
    unsigned n, digit = 0;
	P1DIR = 0xff;
	P1OUT = 0x00;
	P3DIR = 0x00;
	P2DIR = 0xff;
	
   while (1){
	   if(digit > 9)
		   digit = 0;
	   P1OUT = digit;
	   P3OUT = digit;
	   digit++;
	   P2OUT = P3IN;
	   for(n=0; n<40000;n++);
   }
 }   
